module.exports = {
  tilesData: [{
    img: 'http://cdn-image.foodandwine.com/sites/default/files/201111-xl-liege-waffles.jpg',
    title: 'Liege Waffles',
    description: 'description',
  }, {
    img: 'https://static1.squarespace.com/static/50a43af2e4b013b04b877d4e/50a48341e4b06eecde88101c/50c183d0e4b08bba8489d091/1434199989721/_MG_9865.jpg',
    title: 'Liege Waffles',
    description: 'description',
  }, {
    img: 'https://www.sweetashoney.co/wp-content/uploads/DSC_0081.jpg',
    title: 'Liege Waffles',
    description: 'description',
  }, {
    img: 'http://1.bp.blogspot.com/-Zg0XbmBG-NI/VCnq3KYS5RI/AAAAAAAAG1s/ri7467hdlKA/s1600/waffle%2Bcover%2BREVISED.jpg',
    title: 'Liege Waffles',
    description: 'description',
  }, {
    img: 'http://www.europeancuisines.com/sites/default/files/Liege_Waffles_Plated_Up.jpg',
    title: 'Liege Waffles',
    description: 'description',
  }, {
    img: 'https://2.bp.blogspot.com/-gvWAv7FO6wI/Vthl0_-QzUI/AAAAAAAAQ8U/CT20sQq_zJc/s1600/DSC_5768.JPG',
    title: 'Liege Waffles',
    description: 'description',
  }, {
    img: 'https://foodydoody.files.wordpress.com/2015/09/dsc_5130.jpg',
    title: 'Liege Waffles',
    description: 'description',
  }, {
    img: 'http://4.bp.blogspot.com/-Yz0eHsyFtLI/VP5dcZrAMyI/AAAAAAAAPLk/-s2uDvuVlEo/s1600/Caramelized%2BWaffles%2B(Liege%2BWaffles)%2B2.jpg',
    title: 'Liege Waffles',
    description: 'description',
  }, ],

  restaurants: [{
    image_url: 'http://s.eatthis-cdn.com/media/images/ext/842849976/greasy-fast-food.jpg',
    review_count: '151 reviews',
    rating: '4 stars',
    url: 'https://www.yelp.com/biz/everest-indian-restaurant-petaluma?osq=Himalayan',
    name: 'Everest Indian Restaurant',
    location: 'Petaluma, CA',
    categories: 'Himalayan',
  }, {
    image_url: 'http://s.eatthis-cdn.com/media/images/ext/842849976/greasy-fast-food.jpg',
    review_count: '151 reviews',
    rating: '4 stars',
    url: 'https://www.yelp.com/biz/everest-indian-restaurant-petaluma?osq=Himalayan',
    name: 'Everest Indian Restaurant',
    location: 'Petaluma, CA',
    categories: 'Himalayan',
  }, {
    image_url: 'http://s.eatthis-cdn.com/media/images/ext/842849976/greasy-fast-food.jpg',
    review_count: '151 reviews',
    rating: '4 stars',
    url: 'https://www.yelp.com/biz/everest-indian-restaurant-petaluma?osq=Himalayan',
    name: 'Everest Indian Restaurant',
    location: 'Petaluma, CA',
    categories: 'Himalayan',
  }, {
    image_url: 'http://s.eatthis-cdn.com/media/images/ext/842849976/greasy-fast-food.jpg',
    review_count: '151 reviews',
    rating: '4 stars',
    url: 'https://www.yelp.com/biz/everest-indian-restaurant-petaluma?osq=Himalayan',
    name: 'Everest Indian Restaurant',
    location: 'Petaluma, CA',
    categories: 'Himalayan',
  }],

  recipes: [{
    name: 'Pizza',
    description: 'description',
    instructions: 'instructions',
    prepTime: '2 hours',
    ingredients: 'ingredients',
    rating: '5 stars',
    url: 'http://www.foodnetwork.com/recipes/alton-brown/pizza-pizzas-recipe4',
  }, {
    name: 'Pizza',
    description: 'description',
    instructions: 'instructions',
    prepTime: '2 hours',
    ingredients: 'ingredients',
    rating: '5 stars',
    url: 'http://www.foodnetwork.com/recipes/alton-brown/pizza-pizzas-recipe4',
  }, {
    name: 'Pizza',
    description: 'description',
    instructions: 'instructions',
    prepTime: '2 hours',
    ingredients: 'ingredients',
    rating: '5 stars',
    url: 'http://www.foodnetwork.com/recipes/alton-brown/pizza-pizzas-recipe4',
  }, {
    name: 'Pizza',
    description: 'description',
    instructions: 'instructions',
    prepTime: '2 hours',
    ingredients: 'ingredients',
    rating: '5 stars',
    url: 'http://www.foodnetwork.com/recipes/alton-brown/pizza-pizzas-recipe4',
  }],
  data: {
    photoURL: 'http://cdn-image.foodandwine.com/sites/default/files/201111-xl-liege-waffles.jpg',
    status: 'success',
    statusCode: 200,
    restaurants: [{
      id: 'peets-coffee-and-tea-san-francisco-98',
      image_url: 'https://s3-media4.fl.yelpcdn.com/bphoto/pdxzGQloGuN_oF38ILjNKQ/o.jpg',
      review_count: 6,
      rating: 4.5,
      url: 'https://www.yelp.com/biz/peets-coffee-and-tea-san-francisco-98?adjust_creative=9LE31kYOAIuy86mbA9kTng&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=9LE31kYOAIuy86mbA9kTng',
      name: 'Peet\'s Coffee & Tea',
      location: '101 Post St San Francisco, CA 94108',
      categories: [Object],
    }, {
      id: 'peets-coffee-and-tea-san-francisco-40',
      image_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/-kjvJFho13OQI6UTIE8ERQ/o.jpg',
      review_count: 68,
      rating: 2.5,
      url: 'https://www.yelp.com/biz/peets-coffee-and-tea-san-francisco-40?adjust_creative=9LE31kYOAIuy86mbA9kTng&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=9LE31kYOAIuy86mbA9kTng',
      name: 'Peet\'s Coffee & Tea',
      location: '845 Market St San Francisco, CA 94103',
      categories: [Object],
    }],
    recipes: [{
      name: 'Double Dark Chocolate Granita',
      prepTime: '35 mins',
      ingredients: [Object],
      rating: 5,
      source: 'Serious Eats',
      url: 'http://www.yummly.co/#recipe/Double-Dark-Chocolate-Granita-Serious-Eats-289023',
    }, {
      name: 'Mint Dark Chocolate Mocha Ice Cream',
      prepTime: '240 mins',
      ingredients: [Object],
      rating: 4,
      source: 'Whole and Heavenly Oven',
      url: 'http://www.yummly.co/#recipe/Mint-Dark-Chocolate-Mocha-Ice-Cream-1824156',
    }, {
      name: 'Easy Cold Brew Coffee Pie',
      prepTime: '370 mins',
      ingredients: [Object],
      rating: 4,
      source: 'The Domestic Rebel',
      url: 'http://www.yummly.co/#recipe/Easy-Cold-Brew-Coffee-Pie-1742421',
    }],
  },
};
